[package]
name = "narwhal_tusk"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
tokio = { version = "1.0", features = ["full"] }
rand = "0.9"
futures = {version =  "0.3", features = ["channel-unbounded"]}
tokio-util = "0.7"